name: Build, test and publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-and-publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build and test
      uses: ./.github/actions/build-and-test
      with:
        github-user: ${{ github.actor }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        github-docker-server: ghcr.io/${{ github.repository_owner }}
