name: Build, test and publish

on:
  push:
    branches: [ main, wip-publish ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-and-publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build and test
      uses: cer/github-build-and-test-action/build-and-test@main

    - name: Kubernetes test
      uses: cer/github-build-and-test-action/k8s-test@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish
      uses: cer/github-build-and-test-action/k8s-publish@main
      with:
        github-token: ${{ secrets.GH_TOKEN }}
        service-name: customer-service
