name: Build, test and publish

on:
  push:
    branches: [ main, wip-publish ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-and-publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build and test
      uses: cer/github-build-and-test-action/build-and-test@main

    - name: Kubernetes test
      uses: cer/github-build-and-test-action/k8s-test@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}


  real-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Helm
      uses: azure/setup-helm@v4

    - name: set build env
      run: |
        BUILD_DATE=$(date -u +'%Y%m%d%H%M%S')
        echo "BUILD_DATE=${BUILD_DATE}" >> "$GITHUB_ENV"
        echo "VERSION=0.1.0-BUILD.${BUILD_DATE?}" >> "$GITHUB_ENV"

    - name: Push images
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: ./manage/push-images.sh ${VERSION?}

    - name: Publish Helm Charts
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ./manage/publish-helm-chart.sh customer-service ${VERSION?} ${VERSION?}
